In [ ]:
import pandas as pd
import numpy as np

:100000, 100000:300000, 300000:500000, 500000:70000, 700000:900000 are the tweets from full.csv for which the class probabilities have been obtained using bert_self-training_iteration 1 model. These files are then checked for threshold. Only the tweets for which the confidence > 95% will be selected for the final self-training iteration dataset.

In [ ]:
df=pd.read_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration2_data/:100000.csv')
print(df.shape)
print(df.isnull().sum())
df.head()

(100000, 5)
date             0
text             0
retweet_count    1
cleaned          0
proba            0
dtype: int64

         date  ...                                              proba
0  2020-04-01  ...  [6.320875399978831e-05, 1.9303170120110735e-05...
1  2020-04-01  ...  [9.228163253283128e-05, 0.00015559261373709887...
2  2020-04-01  ...  [3.366312739672139e-05, 6.36534605291672e-05, ...
3  2020-04-01  ...  [0.9630545973777771, 0.0003808220790233463, 0....
4  2020-04-01  ...  [9.817126556299627e-05, 5.664761192747392e-05,...

[5 rows x 5 columns]

In [ ]:
df1=pd.read_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration2_data/100000:300000.csv')
df1=df1.iloc[:,[0,1,2,3,5]]
print(df1.shape)
print(df1.isnull().sum())
df1.head()

(200000, 5)
date             0
text             0
retweet_count    4
cleaned          0
proba            0
dtype: int64

         date  ...                                              proba
0  2020-04-02  ...  [6.789106919313781e-06, 2.2915923182154074e-05...
1  2020-04-02  ...  [7.794891644152813e-06, 1.7781820133677684e-05...
2  2020-04-02  ...  [0.00040600524516776204, 0.0011023518163710833...
3  2020-04-02  ...  [0.0002740883210208267, 0.006588350515812635, ...
4  2020-04-02  ...  [0.0006568433018401265, 0.024964338168501854, ...

[5 rows x 5 columns]

In [ ]:
df2=pd.read_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration2_data/300000:500000.csv')
df2=df2.iloc[:,[0,1,2,3,5]]
print(df2.shape)
print(df2.isnull().sum())
df2.head()

(200000, 5)
date             0
text             0
retweet_count    3
cleaned          0
proba            0
dtype: int64

         date  ...                                              proba
0  2020-04-04  ...  [1.0282360562996473e-05, 1.42996514114202e-05,...
1  2020-04-04  ...  [2.1732797904405743e-05, 3.828437547781505e-05...
2  2020-04-04  ...  [2.2669242753181607e-05, 5.258410965325311e-05...
3  2020-04-04  ...  [0.0011912873014807701, 0.02257756143808365, 0...
4  2020-04-04  ...  [1.134413560066605e-05, 2.381124249950517e-05,...

[5 rows x 5 columns]

In [ ]:
df3=pd.read_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration2_data/500000:700000.csv')
df3=df3.iloc[:,[0,1,2,3,5]]
print(df3.shape)
print(df3.isnull().sum())
df3.head()

(200000, 5)
date             0
text             0
retweet_count    1
cleaned          0
proba            0
dtype: int64

         date  ...                                              proba
0  2020-04-06  ...  [0.0067436289973556995, 0.01658712700009346, 0...
1  2020-04-06  ...  [0.3660729229450226, 0.009817938320338726, 0.2...
2  2020-04-06  ...  [0.10052680224180222, 0.009605825878679752, 0....
3  2020-04-06  ...  [0.11064951866865158, 0.008295392617583275, 0....
4  2020-04-06  ...  [5.016967043047771e-05, 0.0002437518269289285,...

[5 rows x 5 columns]

In [ ]:
df4=pd.read_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration2_data/700000:900000.csv')
df4=df4.iloc[:,[0,1,2,3,5]]
print(df4.shape)
print(df4.isnull().sum())
df4.head()

(200000, 5)
date             0
text             0
retweet_count    6
cleaned          0
proba            0
dtype: int64

         date  ...                                              proba
0  2020-04-08  ...  [0.007609003223478794, 0.0021266574040055275, ...
1  2020-04-08  ...  [0.002577709499746561, 0.013099743984639645, 0...
2  2020-04-08  ...  [0.0209425650537014, 0.015494921244680882, 0.0...
3  2020-04-08  ...  [0.007821167819201946, 0.0004949819995090365, ...
4  2020-04-08  ...  [9.552803021506406e-06, 9.788829629542306e-06,...

[5 rows x 5 columns]

In [ ]:
f=pd.concat([df,df1,df2,df3,df4])
print(f.shape)
print(f.isnull().sum())
f.head()

(900000, 5)
date              0
text              0
retweet_count    15
cleaned           0
proba             0
dtype: int64

         date  ...                                              proba
0  2020-04-01  ...  [6.320875399978831e-05, 1.9303170120110735e-05...
1  2020-04-01  ...  [9.228163253283128e-05, 0.00015559261373709887...
2  2020-04-01  ...  [3.366312739672139e-05, 6.36534605291672e-05, ...
3  2020-04-01  ...  [0.9630545973777771, 0.0003808220790233463, 0....
4  2020-04-01  ...  [9.817126556299627e-05, 5.664761192747392e-05,...

[5 rows x 5 columns]

In [ ]:
f1=f.reset_index(drop=True)
f1.tail()

              date  ...                                              proba
899995  2020-04-11  ...  [5.0383190682623535e-05, 0.0001627228630241006...
899996  2020-04-11  ...  [6.0680555179715157e-05, 0.0002587199560366571...
899997  2020-04-11  ...  [0.9754806756973267, 0.0009562870254740119, 0....
899998  2020-04-11  ...  [0.00012445425090845674, 0.0002516330860089510...
899999  2020-04-11  ...  [2.9073344194330275e-05, 3.370550984982401e-05...

[5 rows x 5 columns]

In [ ]:
def findmax(row):
  row=row.replace('[','')
  row=row.replace(']','')
  lt=row.split(',')
  lt=list(map(str.strip,lt))
  l=list(map(float,lt))
  m=max(l)
  i=l.index(m)
  l1=['joy', 'sadness', 'fear', 'anger', 'neutral']
  emotion=l1[i]
  f=[m*100,i,emotion]
  return f

In [ ]:
f1['f']=f1['proba'].apply(findmax)

In [ ]:
f1.head()

         date  ...                                f
0  2020-04-01  ...  [99.97870326042175, 4, neutral]
1  2020-04-01  ...  [99.96435642242432, 4, neutral]
2  2020-04-01  ...  [99.98255372047424, 4, neutral]
3  2020-04-01  ...      [96.30545973777771, 0, joy]
4  2020-04-01  ...  [99.96815919876099, 4, neutral]

[5 rows x 6 columns]

In [ ]:
f1[['confidence','index','emotion']] = pd.DataFrame(f1.f.tolist(), index= f1.index)

In [ ]:
f1.head()

         date  ...  emotion
0  2020-04-01  ...  neutral
1  2020-04-01  ...  neutral
2  2020-04-01  ...  neutral
3  2020-04-01  ...      joy
4  2020-04-01  ...  neutral

[5 rows x 9 columns]

In [ ]:
f2=f1[f1['confidence']>95]
f2=f2.reset_index(drop=True)
f2.head()

         date  ...  emotion
0  2020-04-01  ...  neutral
1  2020-04-01  ...  neutral
2  2020-04-01  ...  neutral
3  2020-04-01  ...      joy
4  2020-04-01  ...  neutral

[5 rows x 9 columns]

In [ ]:
f2.shape

(630917, 9)

In [ ]:
f2['emotion'].value_counts()

neutral    562128
fear        33569
joy         23092
anger        7992
sadness      4136
Name: emotion, dtype: int64

In [ ]:
neutral=f2[f2['emotion']=='neutral']
neutral=neutral.sort_values(by='confidence',ascending=[False])
neutral=neutral.reset_index(drop=True)
neutral.head()

         date  ...  emotion
0  2020-04-03  ...  neutral
1  2020-04-02  ...  neutral
2  2020-04-07  ...  neutral
3  2020-04-01  ...  neutral
4  2020-04-05  ...  neutral

[5 rows x 9 columns]

In [ ]:
fear=f2[f2['emotion']=='fear']
fear=fear.sort_values(by='confidence',ascending=[False])
fear=fear.reset_index(drop=True)
fear.head()

         date                                               text  ...  index emotion
0  2020-04-05  Dushman bhi taarif karne laga hamare @airindia...  ...      2    fear
1  2020-04-04  When it rains during summer months:\nIn normal...  ...      2    fear
2  2020-04-09  Very important advisory to keep a tab on #Fake...  ...      2    fear
3  2020-04-10  Look how this Muslim *journalist * is sufferin...  ...      2    fear
4  2020-04-06  @MumbaiMirror G/S ward there is nt only worli ...  ...      2    fear

[5 rows x 9 columns]

In [ ]:
joy=f2[f2['emotion']=='joy']
joy=joy.sort_values(by='confidence',ascending=[False])
joy=joy.reset_index(drop=True)
joy.head()

         date                                               text  ...  index emotion
0  2020-04-04  Gives us such joy to watch this! https://t.co/...  ...      0     joy
1  2020-04-01  It has been a rough two weeks and this brought...  ...      0     joy
2  2020-04-01  Find joy in working from wherever you are - wi...  ...      0     joy
3  2020-04-02  Surprised and Happy for this development https...  ...      0     joy
4  2020-04-05  I can literally feel the happiness behind thos...  ...      0     joy

[5 rows x 9 columns]

In [ ]:
anger=f2[f2['emotion']=='anger']
anger=anger.sort_values(by='confidence',ascending=[False])
anger=anger.reset_index(drop=True)
anger.head()

         date                                               text  ...  index emotion
0  2020-04-10  @CoffyBiteIndia She: Did you buy me #CoffyBite...  ...      3   anger
1  2020-04-04  I promise I am not just saying this because th...  ...      3   anger
2  2020-04-04  😂 Rafael be fuming to have lost once out 20 ti...  ...      3   anger
3  2020-04-05  I can’t even describe how angry this makes me....  ...      3   anger
4  2020-04-02  @KapilMishra_IND Bitter Reality #Covid19 https...  ...      3   anger

[5 rows x 9 columns]

In [ ]:
sadness=f2[f2['emotion']=='sadness']
sadness=sadness.sort_values(by='confidence',ascending=[False])
sadness=sadness.reset_index(drop=True)
sadness.head()

         date  ...  emotion
0  2020-04-01  ...  sadness
1  2020-04-07  ...  sadness
2  2020-04-01  ...  sadness
3  2020-04-03  ...  sadness
4  2020-04-08  ...  sadness

[5 rows x 9 columns]

In [ ]:
n_train=neutral.iloc[:3000,:]
n_train=n_train.reset_index(drop=True)
print(n_train.shape)
print(n_train.isnull().sum())
n_train.tail()

(3000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

            date  ...  emotion
2995  2020-04-09  ...  neutral
2996  2020-04-01  ...  neutral
2997  2020-04-05  ...  neutral
2998  2020-04-10  ...  neutral
2999  2020-04-08  ...  neutral

[5 rows x 9 columns]

In [ ]:
n_test=neutral.iloc[3000:4000,:]
n_test=n_test.reset_index(drop=True)
print(n_test.shape)
print(n_test.isnull().sum())
n_test.tail()

(1000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

           date  ...  emotion
995  2020-04-10  ...  neutral
996  2020-04-08  ...  neutral
997  2020-04-07  ...  neutral
998  2020-04-10  ...  neutral
999  2020-04-01  ...  neutral

[5 rows x 9 columns]

In [ ]:
f_train=fear.iloc[:3000,:]
f_train=f_train.reset_index(drop=True)
print(f_train.shape)
print(f_train.isnull().sum())
f_train.tail()

(3000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

            date  ... emotion
2995  2020-04-03  ...    fear
2996  2020-04-06  ...    fear
2997  2020-04-01  ...    fear
2998  2020-04-05  ...    fear
2999  2020-04-07  ...    fear

[5 rows x 9 columns]

In [ ]:
f_test=fear.iloc[3000:4000,:]
f_test=f_test.reset_index(drop=True)
print(f_test.shape)
print(f_test.isnull().sum())
f_test.tail()

(1000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

           date  ... emotion
995  2020-04-08  ...    fear
996  2020-04-02  ...    fear
997  2020-04-06  ...    fear
998  2020-04-03  ...    fear
999  2020-04-10  ...    fear

[5 rows x 9 columns]

In [ ]:
j_train=joy.iloc[:3000,:]
j_train=j_train.reset_index(drop=True)
print(j_train.shape)
print(j_train.isnull().sum())
j_train.tail()

(3000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

            date  ... emotion
2995  2020-04-05  ...     joy
2996  2020-04-08  ...     joy
2997  2020-04-02  ...     joy
2998  2020-04-04  ...     joy
2999  2020-04-09  ...     joy

[5 rows x 9 columns]

In [ ]:
j_test=joy.iloc[3000:4000,:]
j_test=j_test.reset_index(drop=True)
print(j_test.shape)
print(j_test.isnull().sum())
j_test.tail()

(1000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

           date  ... emotion
995  2020-04-03  ...     joy
996  2020-04-06  ...     joy
997  2020-04-05  ...     joy
998  2020-04-06  ...     joy
999  2020-04-04  ...     joy

[5 rows x 9 columns]

In [ ]:
a_train=anger.iloc[:3000,:]
a_train=a_train.reset_index(drop=True)
print(a_train.shape)
print(a_train.isnull().sum())
a_train.tail()

(3000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

            date  ... emotion
2995  2020-04-09  ...   anger
2996  2020-04-04  ...   anger
2997  2020-04-10  ...   anger
2998  2020-04-05  ...   anger
2999  2020-04-09  ...   anger

[5 rows x 9 columns]

In [ ]:
a_test=anger.iloc[3000:4000,:]
a_test=a_test.reset_index(drop=True)
print(a_test.shape)
print(a_test.isnull().sum())
a_test.tail()

(1000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

           date  ... emotion
995  2020-04-02  ...   anger
996  2020-04-10  ...   anger
997  2020-04-11  ...   anger
998  2020-04-03  ...   anger
999  2020-04-03  ...   anger

[5 rows x 9 columns]

In [ ]:
s_train=sadness.iloc[:3000,:]
s_train=s_train.reset_index(drop=True)
print(s_train.shape)
print(s_train.isnull().sum())
s_train.tail()

(3000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

            date  ...  emotion
2995  2020-04-10  ...  sadness
2996  2020-04-02  ...  sadness
2997  2020-04-08  ...  sadness
2998  2020-04-01  ...  sadness
2999  2020-04-03  ...  sadness

[5 rows x 9 columns]

In [ ]:
s_test=sadness.iloc[3000:4000,:]
s_test=s_test.reset_index(drop=True)
print(s_test.shape)
print(s_test.isnull().sum())
s_test.tail()

(1000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

           date  ...  emotion
995  2020-04-06  ...  sadness
996  2020-04-02  ...  sadness
997  2020-04-09  ...  sadness
998  2020-04-05  ...  sadness
999  2020-04-07  ...  sadness

[5 rows x 9 columns]

In [ ]:
old=pd.read_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration1_data/train_f_n.csv')
print(old.shape)
print(old.isnull().sum())
old.head()

(11231, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0    anger  When I heard that I was not to be provided wit...
1  sadness  @GoPro your UX online is appalling! No clear s...
2  sadness   We'll get to go fishing at the river . I hate...
3      joy                    Hi , Mary , long time no see .
4    anger    To my great annoyance I found myself jealous .

In [ ]:
on=old[old['Emotion']=='neutral']
print(on.shape)
print(on.isnull().sum())
on.head()

(2184, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
8   neutral   The weather report says it's going to rain fo...
17  neutral                 On the contrary , very exciting .
39  neutral                                          Then ...
49  neutral                                   Not only that !
83  neutral                                 how was your day ?

In [ ]:
os=old[old['Emotion']=='sadness']
print(os.shape)
print(os.isnull().sum())
os.head()

(2185, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
1   sadness  @GoPro your UX online is appalling! No clear s...
2   sadness   We'll get to go fishing at the river . I hate...
6   sadness            You know that my father is irritable .
9   sadness  When my basket ball team lost the qualificatio...
14  sadness  I wish I could live in y'all reality where i c...

In [ ]:
of=old[old['Emotion']=='fear']
print(of.shape)
print(of.isnull().sum())
of.head()

(2361, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
18    fear             My anxiety is playing around HELP!!!!!
22    fear  @CBSThisMorning @newsgirl123456 again, profili...
29    fear  @AnthonyEinzig I'm so sorry. This is heartbrea...
32    fear       Super shitting it about this tattoo #nervous
43    fear  My father was away from home and he did not co...

In [ ]:
oj=old[old['Emotion']=='joy']
print(oj.shape)
print(oj.isnull().sum())
oj.head()

(2287, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
3      joy                    Hi , Mary , long time no see .
7      joy  It was the first time I met him (my boyfriend ...
10     joy  The contrast with her exhilaration on the froz...
12     joy              Oh ! That's much hetter than I did .
16     joy  @INCIndia Oh please! INC talking about looting...

In [ ]:
oa=old[old['Emotion']=='anger']
print(oa.shape)
print(oa.isnull().sum())
oa.head()

(2214, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0    anger  When I heard that I was not to be provided wit...
4    anger    To my great annoyance I found myself jealous .
5    anger  I had too much homework and examinations and I...
11   anger   I really hope that you didn't expect me to pa...
13   anger  His parents were furious over the engagement b...

In [ ]:
on_train=on.iloc[:1000,:]
on_train=on_train.reset_index(drop=True)
print(on_train.shape)
print(on_train.isnull().sum())
on_train.tail()

(1000, 2)
Emotion    0
Text       0
dtype: int64

     Emotion                                               Text
995  neutral   I would think this was the least they could d...
996  neutral                                         Alright .
997  neutral   I ’ Ve got 30 cousins on my mom ’ s side and ...
998  neutral                                            yeah .
999  neutral                                      I did that .

In [ ]:
os_train=os.iloc[:1000,:]
os_train=os_train.reset_index(drop=True)
print(os_train.shape)
print(os_train.isnull().sum())
os_train.tail()

(1000, 2)
Emotion    0
Text       0
dtype: int64

     Emotion                                               Text
995  sadness  She was becoming increasingly despondent about...
996  sadness  When an uncle of mine, who was close to me, pa...
997  sadness  Too many are on their 'yeah, the thing going o...
998  sadness  After having left the company of someone who g...
999  sadness   now that I look back at it , it wawsn't that ...

In [ ]:
of_train=of.iloc[:1000,:]
of_train=of_train.reset_index(drop=True)
print(of_train.shape)
print(of_train.isnull().sum())
of_train.tail()

(1000, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
995    fear  At the railway station, while waiting for the ...
996    fear  @CP24 And I hope when the police met him at th...
997    fear  I don't very often feel frightened , but then ...
998    fear  I was afraid when I learnt that my father was ...
999    fear  I wish I could fast forward 3 months from now,...

In [ ]:
oa_train=oa.iloc[:1000,:]
oa_train=oa_train.reset_index(drop=True)
print(oa_train.shape)
print(oa_train.isnull().sum())
oa_train.tail()

(1000, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
995   anger  You won ’ t believe who ’ s been elected to do...
996   anger  Have wee pop socks on and they KEEP FALLING OF...
997   anger              How dare you question my statement !
998   anger  I felt anger against a person who told bad thi...
999   anger   that seems like an awful waste ! Why don't pe...

In [ ]:
oj_train=oj.iloc[:1000,:]
oj_train=oj_train.reset_index(drop=True)
print(oj_train.shape)
print(oj_train.isnull().sum())
oj_train.tail()

(1000, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
995     joy  When my brother came back home after staying i...
996     joy  @beautyfulli_ami that guy in the back of your ...
997     joy                         How's your married life ?
998     joy  I worked at a lawyer's office during Summer an...
999     joy        You look so happy , Anna . Any good news ?

In [ ]:
on_test=on.iloc[1000:1500,:]
on_test=on_test.reset_index(drop=True)
print(on_test.shape)
print(on_test.isnull().sum())
on_test.tail()

(500, 2)
Emotion    0
Text       0
dtype: int64

     Emotion                                               Text
495  neutral  Coronavirus Outbreak: Additional COVID-19 case...
496  neutral  BBC News - Coronavirus: South Korea sect leade...
497  neutral  President Trump, in a tweet, announces people ...
498  neutral  Gorakhpur organises â€˜chicken melaâ€™ to disp...
499  neutral  @WHO This brings the ðŸŒŽ total of laboratory-...

In [ ]:
os_test=os.iloc[1000:1500,:]
os_test=os_test.reset_index(drop=True)
print(os_test.shape)
print(os_test.isnull().sum())
os_test.tail()

(500, 2)
Emotion    0
Text       0
dtype: int64

     Emotion                                               Text
495  sadness  He was not overwhelmed with grief for Kit , bu...
496  sadness                  No , sir . I'm sorry you can't .
497  sadness  Condolences to the  JC and the Georges family....
498  sadness  When I first heard that Tage Dannielsson had d...
499  sadness  My mother was working with a knife and we were...

In [ ]:
oj_test=oj.iloc[1000:1500,:]
oj_test=oj_test.reset_index(drop=True)
print(oj_test.shape)
print(oj_test.isnull().sum())
oj_test.tail()

(500, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
495     joy             Ever wake up and instantly feel happy?
496     joy  @BattleSmitten \n\nother begin telling a 'stor...
497     joy  Watch this amazing live.ly broadcast by @swagr...
498     joy   The seats in the middle of this stadium are g...
499     joy   Well , I like collecting matchbox ! I'm not s...

In [ ]:
of_test=of.iloc[1000:1500,:]
of_test=of_test.reset_index(drop=True)
print(of_test.shape)
print(of_test.isnull().sum())
of_test.tail()

(500, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
495    fear  Andrew's hands start shaking and he says 'I ho...
496    fear  #PeopleLikeMeBecause they see the happy exteri...
497    fear     I'm not actually writing a physics exam today
498    fear  Sometimes we the decisions that are the most d...
499    fear  This brother know we know that his life was no...

In [ ]:
oa_test=oa.iloc[1000:1500,:]
oa_test=oa_test.reset_index(drop=True)
print(oa_test.shape)
print(oa_test.isnull().sum())
oa_test.tail()

(500, 2)
Emotion    0
Text       0
dtype: int64

    Emotion                                               Text
495   anger  the girl sitting in front of me is chewing her...
496   anger                    Very well , consider me gone .
497   anger  Fucking hell. Rush for the damn train also no ...
498   anger  @LynneGarrison yeah, I've only seen that float...
499   anger   yes . Last Sunday I went to a nearby market ....

In [ ]:
train_set=pd.concat([n_train,f_train,j_train,a_train,s_train])
train_set=train_set.reset_index(drop=True)
print(train_set.shape)
print(train_set.isnull().sum())
train_set.tail()

(15000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

             date  ...  emotion
14995  2020-04-10  ...  sadness
14996  2020-04-02  ...  sadness
14997  2020-04-08  ...  sadness
14998  2020-04-01  ...  sadness
14999  2020-04-03  ...  sadness

[5 rows x 9 columns]

In [ ]:
test_set=pd.concat([n_test,f_test,j_test,a_test,s_test])
test_set=test_set.reset_index(drop=True)
print(test_set.shape)
print(test_set.isnull().sum())
test_set.tail()

(5000, 9)
date             0
text             0
retweet_count    0
cleaned          0
proba            0
f                0
confidence       0
index            0
emotion          0
dtype: int64

            date  ...  emotion
4995  2020-04-06  ...  sadness
4996  2020-04-02  ...  sadness
4997  2020-04-09  ...  sadness
4998  2020-04-05  ...  sadness
4999  2020-04-07  ...  sadness

[5 rows x 9 columns]

In [ ]:
tr=train_set.iloc[:,[8,3]]
print(tr.head())
tr.columns=['Emotion','Text']
print(tr.shape)
print(tr.isnull().sum())
tr.head()

   emotion                                            cleaned
0  neutral  I think they should start the testing there. L...
1  neutral  What about the "Planned Spread" of #Coronaviru...
2  neutral  A close look at the numbers reveal India has r...
3  neutral  Scientists in different parts of the World are...
4  neutral  What treatments and drugs are being developed,...
(15000, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0  neutral  I think they should start the testing there. L...
1  neutral  What about the "Planned Spread" of #Coronaviru...
2  neutral  A close look at the numbers reveal India has r...
3  neutral  Scientists in different parts of the World are...
4  neutral  What treatments and drugs are being developed,...

In [ ]:
te=test_set.iloc[:,[8,3]]
print(te.head())
te.columns=['Emotion','Text']
print(te.shape)
print(te.isnull().sum())
te.head()

   emotion                                            cleaned
0  neutral  1. Let's go. BREAK: Officially, Spain moves up...
1  neutral  #TipsToFightCorona\n ji\n \nIndian culture pro...
2  neutral  Africa is still weeks away from the height of ...
3  neutral  Nature Medicine summarizes all the research yo...
4  neutral  “As President ⁦ ⁩ mobilizes the nation to comb...
(5000, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0  neutral  1. Let's go. BREAK: Officially, Spain moves up...
1  neutral  #TipsToFightCorona\n ji\n \nIndian culture pro...
2  neutral  Africa is still weeks away from the height of ...
3  neutral  Nature Medicine summarizes all the research yo...
4  neutral  “As President ⁦ ⁩ mobilizes the nation to comb...

In [ ]:
f_tr=pd.concat([tr,on_train,os_train,of_train,oa_train,oj_train])
print(f_tr.shape)
print(f_tr.isnull().sum())
f_tr.head()

(20000, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0  neutral  I think they should start the testing there. L...
1  neutral  What about the "Planned Spread" of #Coronaviru...
2  neutral  A close look at the numbers reveal India has r...
3  neutral  Scientists in different parts of the World are...
4  neutral  What treatments and drugs are being developed,...

In [ ]:
f_te=pd.concat([te,on_test,os_test,of_test,oa_test,oj_test])
print(f_te.shape)
print(f_te.isnull().sum())
f_te.head()

(7500, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0  neutral  1. Let's go. BREAK: Officially, Spain moves up...
1  neutral  #TipsToFightCorona\n ji\n \nIndian culture pro...
2  neutral  Africa is still weeks away from the height of ...
3  neutral  Nature Medicine summarizes all the research yo...
4  neutral  “As President ⁦ ⁩ mobilizes the nation to comb...

In [ ]:
f_tr1=f_tr.drop_duplicates(subset=['Text'])
print(f_tr1.shape)
print(f_tr1.isnull().sum())
f_tr1.head()

(19364, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0  neutral  I think they should start the testing there. L...
1  neutral  What about the "Planned Spread" of #Coronaviru...
2  neutral  A close look at the numbers reveal India has r...
3  neutral  Scientists in different parts of the World are...
4  neutral  What treatments and drugs are being developed,...

In [ ]:
f_te1=f_te.drop_duplicates(subset=['Text'])
print(f_te1.shape)
print(f_te1.isnull().sum())
f_te1.head()

(7222, 2)
Emotion    0
Text       0
dtype: int64

   Emotion                                               Text
0  neutral  1. Let's go. BREAK: Officially, Spain moves up...
1  neutral  #TipsToFightCorona\n ji\n \nIndian culture pro...
2  neutral  Africa is still weeks away from the height of ...
3  neutral  Nature Medicine summarizes all the research yo...
4  neutral  “As President ⁦ ⁩ mobilizes the nation to comb...

In [ ]:
s_tr=f_tr1.sample(frac=1)
s_te=f_te1.sample(frac=1)

In [ ]:
print(s_tr.shape)
print(s_te.shape)
print(s_tr.isnull().sum())
print(s_te.isnull().sum())

(19364, 2)
(7222, 2)
Emotion    0
Text       0
dtype: int64
Emotion    0
Text       0
dtype: int64

In [ ]:
s_tr.head()

       Emotion                                               Text
5119      fear  It has been a trend for leftists to criticize ...
10357    anger  Spitting on people who are saving your lives? ...
89       anger  You complain all the time and then wonder why ...
2599   neutral  The #Coronavirus pandemic proves that crises c...
908       fear  And you feel anxious about getting the first l...

In [ ]:
s_te.head()

      Emotion                                               Text
308     anger  That's really it for my madden career that gam...
2872      joy                        Heyy congrats yall did it 😤
1188     fear  Situation seems to be horrible as per data sho...
479   neutral  Latest on #Coronavirus is that cases have emer...
855   neutral  I've just posted a new blog: Satoshi Nakaboto:...

In [ ]:
s_tr=s_tr.reset_index(drop=True)
s_te=s_te.reset_index(drop=True)

In [ ]:
s_tr.to_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration2_data/train_set.csv',index=False)
s_te.to_csv('/content/drive/My Drive/IBM_sentiment_analysis/classification_sentiment_analysis/datasets/self-training_iteration2_data/test_set.csv',index=False)