In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv('/content/drive/My Drive/IBM_sentiment_analysis/data/labelled_positive_negative_neutral.csv')
print(df.shape)
print(df.isnull().sum())
df.head()

(4185573, 4)
date         0
text         0
cleaned      0
sentiment    0
dtype: int64

         date  ... sentiment
0  2020-04-01  ...         1
1  2020-04-01  ...         1
2  2020-04-01  ...         0
3  2020-04-01  ...         1
4  2020-04-01  ...         1

[5 rows x 4 columns]

In [ ]:
searchfor = ['economy','economycollapse','economy collapse','financialcrisis','financial crisis','debt']

In [ ]:
df1=df[df['cleaned'].str.contains('|'.join(searchfor))]
print(df1.shape)
print(df1.isnull().sum())
df1.head()

(44729, 4)
date         0
text         0
cleaned      0
sentiment    0
dtype: int64

            date  ... sentiment
391   2020-04-01  ...        -1
533   2020-04-01  ...        -1
575   2020-04-01  ...         0
647   2020-04-01  ...         1
1024  2020-04-01  ...        -1

[5 rows x 4 columns]

In [ ]:
df2=df1.reset_index(drop=True)
print(df2.shape)
df2.head()

(44729, 4)

         date  ... sentiment
0  2020-04-01  ...        -1
1  2020-04-01  ...        -1
2  2020-04-01  ...         0
3  2020-04-01  ...         1
4  2020-04-01  ...        -1

[5 rows x 4 columns]

In [ ]:
len(df2['date'].unique())

90

In [ ]:
import datetime
full=[]
summ=0
start_date = datetime.date(2020, 2, 1)
end_date = datetime.date(2020, 4, 30)
delta = datetime.timedelta(days=1)
while start_date <= end_date:
    temp=df2[df2['date']==str(start_date)]
    neu=temp[temp['sentiment']==0]
    pos=temp[temp['sentiment']==1]
    neg=temp[temp['sentiment']==-1]
    neu_c=neu.shape[0]
    pos_c=pos.shape[0]
    neg_c=neg.shape[0]
    total=neu_c+pos_c+neg_c
    if(total!=0):
      neu_cp=(neu_c/total)*100
      pos_cp=(pos_c/total)*100
      neg_cp=(neg_c/total)*100
    else:
      neu_cp=0
      pos_cp=0
      neg_cp=0

    row=[start_date,neu_c,pos_c,neg_c,total,neu_cp,pos_cp,neg_cp]
    full.append(row)
    summ=summ+neu_c+pos_c+neg_c
    start_date += delta
    print(start_date)

2020-02-02
2020-02-03
2020-02-04
2020-02-05
2020-02-06
2020-02-07
2020-02-08
2020-02-09
2020-02-10
2020-02-11
2020-02-12
2020-02-13
2020-02-14
2020-02-15
2020-02-16
2020-02-17
2020-02-18
2020-02-19
2020-02-20
2020-02-21
2020-02-22
2020-02-23
2020-02-24
2020-02-25
2020-02-26
2020-02-27
2020-02-28
2020-02-29
2020-03-01
2020-03-02
2020-03-03
2020-03-04
2020-03-05
2020-03-06
2020-03-07
2020-03-08
2020-03-09
2020-03-10
2020-03-11
2020-03-12
2020-03-13
2020-03-14
2020-03-15
2020-03-16
2020-03-17
2020-03-18
2020-03-19
2020-03-20
2020-03-21
2020-03-22
2020-03-23
2020-03-24
2020-03-25
2020-03-26
2020-03-27
2020-03-28
2020-03-29
2020-03-30
2020-03-31
2020-04-01
2020-04-02
2020-04-03
2020-04-04
2020-04-05
2020-04-06
2020-04-07
2020-04-08
2020-04-09
2020-04-10
2020-04-11
2020-04-12
2020-04-13
2020-04-14
2020-04-15
2020-04-16
2020-04-17
2020-04-18
2020-04-19
2020-04-20
2020-04-21
2020-04-22
2020-04-23
2020-04-24
2020-04-25
2020-04-26
2020-04-27
2020-04-28
2020-04-29
2020-04-30
2020-05-01

In [ ]:
print(summ)

44729

In [ ]:
dff=pd.DataFrame(full,columns=['date','neutral_count','positive_count','negative_count','total','neutral_count_pct','positive_count_pct','negative_count_pct'])
print(dff.shape)
print(dff.isnull().sum())
dff.head()

(90, 8)
date                  0
neutral_count         0
positive_count        0
negative_count        0
total                 0
neutral_count_pct     0
positive_count_pct    0
negative_count_pct    0
dtype: int64

         date  neutral_count  ...  positive_count_pct  negative_count_pct
0  2020-02-01              8  ...           33.333333           44.444444
1  2020-02-02             19  ...           26.562500           43.750000
2  2020-02-03             15  ...           31.730769           53.846154
3  2020-02-04             14  ...           31.168831           50.649351
4  2020-02-05             19  ...           21.212121           50.000000

[5 rows x 8 columns]

In [ ]:
dff.tail()

          date  neutral_count  ...  positive_count_pct  negative_count_pct
85  2020-04-26            141  ...           46.161417           39.960630
86  2020-04-27            231  ...           45.073701           37.005431
87  2020-04-28            162  ...           44.384546           41.060198
88  2020-04-29            166  ...           39.407540           45.691203
89  2020-04-30            246  ...           44.465649           39.885496

[5 rows x 8 columns]

In [ ]:
dff.to_csv('/content/drive/My Drive/IBM_sentiment_analysis/critical_topics/pos_neg_plots/economy_pos_neg.csv',index=False)